### ISSUE TITLE
setNotificationClickListener not working in IOS

### ISSUE THREAD

**Issue by jothikannan** [pushy-me/pushy-react-native#38]
I need to listen to the Push notification when a user clicking on it. So I used setNotificationClickListener to listen on user click, but unfortunately, I am not getting any response on it.

```
import Pushy from 'pushy-react-native';
// Pushy Notification Listener (HeadlessJS)
// Invoked even if your app is in the background
Pushy.setNotificationListener(async (data) => {
  // Print notification payload data
  console.log('Received notification: ' + JSON.stringify(data));

  // Notification title
  let notificationTitle = 'Home Builder';

  // Attempt to extract the "message" property from the payload: {"message":"Hello World!"}
  let notificationText = data.message || 'Test notification';

  // Display basic system notification
  Pushy.notify(notificationTitle, notificationText, data);
});

// Pushy Notification Click Listener
Pushy.setNotificationClickListener(async (data) => {
  // Display basic alert
   alert('Clicked notification: ' + data.message);
    NavigationActions.navigate("Dashboard");
  // Navigate the user to another page or 
  // execute other logic on notification click
});
```
and I have 

```
  componentDidMount() {
    // Start the Pushy service
    Pushy.listen();
  }
```

```
    "native-base": "^2.13.8",
    "pushy-react-native": "^1.0.14",
    "react": "16.9.0",
    "react-native": "0.61.5",
```

**Comment by pushy-me** [comment]
Hi @jothikannan,
Where are you calling Pushy.listen() in your app?

Please make sure to invoke it first thing in your `App.js`'s `componentDidMount()` method.

Also, can you paste your entire `App.js` file contents?

**Comment by jothikannan** [comment]
@pushy-me 

Yes I am calling Pushy.listen() in my App.js

```
import React, {Component} from 'react';
import 'react-native-gesture-handler';
import Pushy from 'pushy-react-native';
import MainStackNavigator from './src/navigation/MainStackNavigator';

// Pushy Notification Listener (HeadlessJS)
// Invoked even if your app is in the background
Pushy.setNotificationListener(async (data) => {
  // Print notification payload data
  console.log('Received notification: ' + JSON.stringify(data));

  // Notification title
  let notificationTitle = 'Pushy';

  // Attempt to extract the "message" property from the payload: {"message":"Hello World!"}
  let notificationText = data.message || 'Test notification';

  // Display basic system notification
  Pushy.notify(notificationTitle, notificationText, data);
});

// Pushy Notification Click Listener
Pushy.setNotificationClickListener(async (data) => {
  // Display basic alert
  alert('Clicked notification: ' + data.message);

  // Navigate the user to another page or 
  // execute other logic on notification click
});

export default class App extends Component{

  componentDidMount() {
    // Start the Pushy service
    Pushy.listen();
  }
  
   render() { 
    return (
       <MainStackNavigator /> 
    )}
}
```

**Comment by jothikannan** [comment]
I got it fixed by following changes in the listener

```
Pushy.setNotificationClickListener(function (data) {
  // Display basic alert
  NavigationActions.navigate('Dashboard');
  // Navigate the user to another page or 
  // execute other logic on notification click
});
```

before it was 
```
Pushy.setNotificationClickListener(async (data) {
  // Display basic alert
  NavigationActions.navigate('Dashboard');
  // Navigate the user to another page or 
  // execute other logic on notification click
});
```

Please update this minor issue in the document please

**Comment by pushy-me** [comment]
Hi @jothikannan,
Are you saying that removing the `async` keyword and using a standard `function` fixed the issue?

**Comment by jothikannan** [comment]
Yes `standard function` fixed the issue

**Comment by pushy-me** [comment]
@jothikannan 

Thanks so much, we're updating the documentation as we speak.

**Comment by ethanyuwang** [comment]
Tried both function declarations and made sure i had this:

```
componentDidMount() {
    // Start the Pushy service
    Pushy.listen();
  }

```
 in my app.js but still not working

**Comment by pushy-me** [comment]
Hi @ethanyuwang,
We've sent a response to the support e-mail you sent regarding this issue. Let's continue investigation there.

**Comment by hhemmati81** [comment]
I have the same problem. Removing async doesn't fix this issue for me either.

**Comment by pushy-me** [comment]
Hi @hhemmati81,
We'd be glad to help investigate.

1) Where are you calling `Pushy.listen()` in your app?

2) Please make sure to invoke it first thing in your `App.js`'s `componentDidMount()` method.

3) Can you paste your entire `App.js` file contents?

4) Please try running the [pushy-demo-react-native](https://github.com/pushy-me/pushy-demo-react-native) to see if the notification click is handled there on your device. Instructions are in the project home page. This would help us check if the issue is happening because of your specific iOS version or if it's an SDK implementation issue.

**Comment by hhemmati81** [comment]
I couldn't get the demo working but I did a sample React Native build with Pushy and it worked fine there. I do use React Native Firebase package and I already added FirebaseAppDelegateProxyEnabled NO to info.plist. 

Here is the content of my App.js
`import React, {useEffect} from 'react';
import {
  NavigationContainer,
  PermissionsAndroid,
} from '@react-navigation/native';
import MainTabBar from './src/navigation/mainTabBar';
import FlashMessage from 'react-native-flash-message';
import RNBootSplash from 'react-native-bootsplash';
import {navigationRef} from './src/components/navigationProps';
import {StatusBar, Platform} from 'react-native';
import Pushy from 'pushy-react-native';
// Only necessary for Android
if (Platform.OS === 'android') {
  // Check whether the user has granted the app the WRITE_EXTERNAL_STORAGE permission
  PermissionsAndroid.check(
    PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
  ).then(granted => {
    if (!granted) {
      // Request the WRITE_EXTERNAL_STORAGE permission so that the Pushy SDK will be able to persist the device token in the external storage
      PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
      ).then(result => {
        // User denied permission?
        if (result !== PermissionsAndroid.RESULTS.GRANTED) {
          // Possibly ask the user to grant the permission
        }
      });
    }
  });
}
// Pushy Notification Listener (HeadlessJS)
// Invoked even if your app is in the background
Pushy.setNotificationListener(data => {
  // Print notification payload data
  console.log('Received notification: ' + JSON.stringify(data));

  // Notification title
  let notificationTitle = 'Pushy';

  // Attempt to extract the "message" property from the payload: {"message":"Hello World!"}
  let notificationText = data.message || 'Test notification';

  // Display basic system notification
  Pushy.notify(notificationTitle, notificationText, data);
});

// Pushy Notification Click Listener
Pushy.setNotificationClickListener(data => {
  // Display basic alert
  console.log('clicked on');
  alert('Clicked notification: ' + data.message);

  // Navigate the user to another page or
  // execute other logic on notification click
});
function App() {
  useEffect(() => {
    Pushy.listen();
    RNBootSplash.hide({duration: 250});

    // Register the user for push notifications
    Pushy.register()
      .then(async deviceToken => {
        // Display an alert with device token
        alert('Pushy device token: ' + deviceToken);

        // Send the token to your backend server via an HTTP GET request
        //await fetch('https://your.api.hostname/register/device?token=' + deviceToken);

        // Succeeded, optionally do something to alert the user
      })
      .catch(err => {
        // Handle registration errors
        console.error(err);
      });
  });
  return (
    <NavigationContainer ref={navigationRef}>
      {Platform.OS === 'ios' ? (
        <StatusBar barStyle="dark-content" translucent={true} />
      ) : null}
      <MainTabBar />
      <FlashMessage position="top" floating={true} />
    </NavigationContainer>
  );
}
export default App;`

**Comment by pushy-me** [comment]
Hi @hhemmati81,
It may indeed be caused by failing to call `Pushy.listen()` in `componentDidMount()` . 

While `useEffect()` is similar, it isn't executed at precisely the same moment as when your app is launched from the notification, and it may explain the reason why your click listener isn't being invoked (as the SDK checks if the app is transitioning from background to foreground to know that a notification was tapped, causing the app to open).

Please try modifying your `Component` to extend `React.Component` as follows:

```
class Example extends React.Component {
  componentDidMount() {
    Pushy.listen();
  }

  render() {
    return (
      <div></div>
    );
  }
}
```

**Comment by hhemmati81** [comment]
I got it to work with a class. I had to also delete the app from the Pushy dashboard and create it again. For Andriod push notifications won't come through if the app is closed unless I do an FCM fallback. Not a big deal but curious to know if that's expected behavior. I have another issue but I will create a new ticket for that since it's unrelated to this. Thanks for the help

**Comment by pushy-me** [comment]
Hi @hhemmati81,
Glad to hear it! 🎉 

As per Android push notification delivery delays, please see this article as it may be caused by multiple reasons (usually Chinese OEMs):
[https://support.pushy.me/hc/en-us/articles/360043864771-Why-are-my-notifications-being-delayed-when-my-Android-app-is-in-the-background-](Why are my notifications delayed when my Android app is in the background?
)
